"""Drive the Streamlit UI headlessly and print a markdown interaction log.

Screenshots are not reproducible; this is. It runs `app.py` through Streamlit's
`AppTest` harness, performs the same clicks a user would, and prints what the
page actually rendered at each step.

    python capture_walkthrough.py > logs/app-walkthrough.md

Steps 3-5 call the Gemini API and need `GEMINI_API_KEY`; the rest run offline.
"""

from __future__ import annotations

import sys
from pathlib import Path

from streamlit.testing.v1 import AppTest

APP = Path(__file__).resolve().parent / "app.py"
WIDTH = 100


def find_button(at: AppTest, text: str):
    for button in at.button:
        if text in button.label:
            return button
    raise LookupError(f"no button matching {text!r}; saw {[b.label for b in at.button]}")


def find_input(at: AppTest, label: str):
    for widget in at.text_input:
        if widget.label == label:
            return widget
    raise LookupError(f"no text input labelled {label!r}")


def clip(text: str, width: int = WIDTH) -> str:
    flat = " ".join(str(text).split())
    return flat if len(flat) <= width else flat[: width - 1] + "…"


def step(number: int, title: str, action: str) -> None:
    print(f"\n## Step {number} — {title}\n")
    print(f"**Action:** {action}\n")


def render(at: AppTest, *, sections: bool = True) -> None:
    """Print the text the page rendered, in document order per element type."""
    print("```")
    if sections:
        for heading in at.subheader:
            print(f"[subheader] {clip(heading.value)}")
    for metric in at.metric:
        delta = f" ({metric.delta})" if metric.delta else ""
        print(f"[metric]    {metric.label}: {metric.value}{delta}")
    for block in at.markdown:
        if block.value.strip():
            print(f"[markdown]  {clip(block.value)}")
    for caption in at.caption:
        if caption.value.strip():
            print(f"[caption]   {clip(caption.value)}")
    for info in at.info:
        print(f"[info]      {clip(info.value)}")
    for warning in at.warning:
        print(f"[warning]   {clip(warning.value)}")
    for error in at.error:
        print(f"[error]     {clip(error.value)}")
    for success in at.success:
        print(f"[success]   {clip(success.value)}")
    print("```")


def domain(at: AppTest, label: str = "Domain state") -> None:
    owner = at.session_state["owner"]
    print(f"\n**{label}:**\n")
    print("```")
    print(f"owner   : {owner.name or '(blank)'}, {owner.available_minutes} min available")
    if not owner.pets:
        print("pets    : (none)")
    for pet in owner.pets:
        print(f"pet     : {pet.name} ({pet.breed})"
              f"{', allergies: ' + ', '.join(pet.allergies) if pet.allergies else ''}")
        for task in pet.tasks:
            start = f"{task.start:%H:%M} " if task.start else ""
            print(f"  task  : {start}{task.name} — {task.duration} min, "
                  f"{task.priority.name.lower()}, {task.status}")
    print("```")


def main() -> int:
    print("# Streamlit UI walkthrough (interaction log)")
    print()
    print("Generated by `python capture_walkthrough.py`, which drives `app.py` through")
    print("Streamlit's `AppTest` harness — the same clicks a user would make, captured")
    print("as text so the run is reproducible rather than a screenshot.")

    at = AppTest.from_file(str(APP), default_timeout=180)
    at.run()

    step(1, "Open the app", "load `app.py` (seeded with the demo owner and pet)")
    render(at)
    domain(at)

    step(2, "Enter this user's details",
         "set the owner name to `Somi`, add a second pet `Rex`, and record a chicken "
         "allergy on the selected pet (Mochi)")
    find_input(at, "Owner name").set_value("Somi").run()
    find_input(at, "Name").set_value("Rex").run()
    find_button(at, "Add pet").click().run()
    find_input(at, "Allergies (comma-separated)").set_value("chicken").run()
    domain(at)

    step(3, "Ask the wellness advisor", "type a focus question and click *Suggest*")
    find_input(at, "Anything specific to focus on?").set_value(
        "he's bored and chewing furniture"
    ).run()
    find_button(at, "Suggest for").click().run()

    # AppTest exposes a plain dict via filtered_state; the proxy itself has no .get().
    routine = next(
        (v for k, v in at.session_state.filtered_state.items() if k.startswith("routine_")),
        None,
    )
    if routine is None:
        print("\n> Generation unavailable (no API key, or the daily quota is spent).")
        print("> Retrieval still ran; the page shows the retrieved passages instead.\n")
        render(at)
    else:
        print("\n**Retrieved passages (the R in RAG):**\n")
        print("```")
        for i, source in enumerate(routine.sources, 1):
            print(f"[{i}] {source.score:.3f}  {source.passage.label}"
                  f"  (knowledge/{source.passage.source})")
        print("```")
        print("\n**Generated routine:**\n")
        print("```")
        print(f"summary : {clip(routine.summary, 400)}")
        for activity in routine.activities:
            print(f"· {activity.name} — {activity.duration_minutes} min, {activity.priority}"
                  + (f", {activity.time_of_day}" if activity.time_of_day else ""))
            print(f"    why: {clip(activity.why, 160)}")
        for caution in routine.cautions:
            print(f"caution : {clip(caution, 160)}")
        print(f"total   : {routine.total_minutes} min of "
              f"{at.session_state['owner'].available_minutes} available")
        print("```")
        print("\n**Guardrail findings:**\n")
        print("```")
        if routine.issues:
            for issue in routine.issues:
                print(f"{issue}")
        else:
            print("(none — every activity was grounded, safe, and within budget)")
        print("```")

    if routine is not None:
        step(4, "Accept the routine", "click *Add … activities to Rex's tasks*")
        find_button(at, "activities to").click().run()
        domain(at, "Tasks after accepting")

    step(5, "Build the schedule", "click *Generate schedule*")
    find_button(at, "Generate schedule").click().run()
    plan = at.session_state.filtered_state.get("plan") or []
    print("\n**Plan produced by the original Module 2 scheduler:**\n")
    print("```")
    if plan:
        for task in plan:
            print(f"{task.start:%H:%M}  {task.name} — {task.duration} min, "
                  f"{task.priority.name.lower()} ({task.pet.name})")
    else:
        print("(nothing scheduled)")
    skipped = [t for t in at.session_state["owner"].all_tasks() if t.status == "skipped"]
    if skipped:
        print(f"skipped: {', '.join(t.name for t in skipped)}")
    print("```")
    render(at, sections=False)

    step(6, "Hand the app to someone else", "*Start over* → *Clear everything*")
    find_button(at, "Clear everything").click().run()
    domain(at, "Domain state after reset")
    render(at)

    if at.exception:
        print("\n## Unhandled exceptions\n")
        print("```")
        for exception in at.exception:
            print(exception.value)
        print("```")
        return 1

    print("\n---\n")
    print("No unhandled exceptions. Every step above is reproducible with the command")
    print("at the top of this file.")
    return 0


if __name__ == "__main__":
    sys.exit(main())
